In [1]:
import os
import numpy as np
import math as m

import matplotlib as plt
%matplotlib inline

from mpl_toolkits.mplot3d import Axes3D

import pandas as pd

import tensorflow as tf

In [2]:
def reset_graph(seed_=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed_)
    np.random.seed(seed_)

In [3]:
n_points_ = 5000
n_features_ = 3

bias_ = np.ones(n_points_).reshape((-1, 1))
low_ = - np.ones(( n_points_, n_features_ ), 'float')
high_ = np.ones(( n_points_, n_features_ ), 'float')  

X = np.random.uniform(low=low_, high=high_)

noise = np.random.normal(size=( n_points_, 1 ))

weights = np.array([1.0, 0.5, 0.2, 0.1])
noise_std = 0.1
Y = weights[0]*bias_ + np.dot(X, weights[1:]).reshape((-1, 1)) + noise_std*noise

train_test_split = 4

n_test = int(n_points_/train_test_split)
n_train = n_points_ - n_test

X_train = X[:n_train, :]
X_test = X[n_train:, :]
Y_train = Y[:n_train].reshape((-1, 1))
Y_test = Y[n_train:].reshape((-1, 1))

In [4]:
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((3750, 3), (3750, 1), (1250, 3), (1250, 1))

In [5]:
## Linear Regression with Numpy

X = np.hstack( (np.ones( n_train ).reshape((-1, 1)), X_train ) )
print(X)
print(len(X))
theta_numpy = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(Y_train)
theta_numpy

[[ 1.          0.36904826  0.37777863  0.28495882]
 [ 1.          0.36266934  0.76433974 -0.64673973]
 [ 1.         -0.89243952 -0.32370441 -0.74121926]
 ...
 [ 1.         -0.71771615 -0.48795524 -0.64065911]
 [ 1.         -0.65040521 -0.93415451  0.94940226]
 [ 1.         -0.75535286 -0.59400173 -0.06627896]]
3750


array([[0.99840536],
       [0.50105529],
       [0.19850041],
       [0.09932483]])

In [6]:
## Linear Regression with Sklearn

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, Y_train)

print(np.r_[lin_reg.intercept_.reshape(-1, 1), lin_reg.coef_.T])

[[0.99840536]
 [0.50105529]
 [0.19850041]
 [0.09932483]]


In [7]:
## Linear Regression with Tensorflow

X_np = np.hstack((np.ones(n_train).reshape((-1, 1)), X_train))

X = tf.constant(X_np, dtype=tf.float32, name='X')
Y = tf.constant(Y_train, dtype=tf.float32, name='Y')
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), Y)

with tf.Session() as sess:
    theta_value = theta.eval()

In [8]:
theta_value

array([[0.9984055 ],
       [0.5010552 ],
       [0.1985004 ],
       [0.09932482]], dtype=float32)

In [9]:
class Model:

    def __init__(self, n_features_, learning_rate_=0.05, L_=0):
        

SyntaxError: unexpected EOF while parsing (<ipython-input-9-19e266c19ba8>, line 4)